### ISSUE TITLE
More Generate Key Options

### ISSUE THREAD

**Issue by akkadaya** [akamai/akr#15]
Is there a way to generate different key types? If not, is it possible to add this option?

Thanks

**Comment by akkadaya** [comment]
is this repo maintained? I can't find any updates or answers from the company? maybe they should give away this product to some organisation which will maintain it!

**Comment by nikhilty** [comment]
wouldn't `ssh-keygen -t <type>` solve this? Let me know if this is still an urgent requirement but i think this can be solved by this command.

**Comment by adampiskorski** [comment]
How would this get loaded onto the mobile app?
For my use case, I need to use ssh-rsa for sites like Azure devops, otherwise, I can't use this service.

**Comment by nikhilty** [comment]
starting release 1.1.0, ssh-agent will pre-load all RSA, ECDSA and ED25519 keys from ~/.ssh directory on start. Let me know if that works for you.

**Comment by nikhilty** [comment]
Closing this issue for now. Let me know if you need assistance.
