### ISSUE TITLE
Debian packages are not found

### ISSUE THREAD

**Issue by lambda-chat** [akamai/akr#16]
https://akamai.github.io/akr-pkg/debian/ returns 404 and I cannot install `akr` to Debian docker image.

The related parts of my Dockerfile (Debian: bullseye):
```Dockerfile
RUN curl -SsL https://akamai.github.io/akr-pkg/debian/KEY.gpg | apt-key add - \
    && curl -SsL -o /etc/apt/sources.list.d/akr.list https://akamai.github.io/akr-pkg/debian/akr.list
RUN apt-get update \
    && apt-get install -y \
    # akr \
```

Some commands and results:
```sh
$ cat /etc/apt/sources.list.d/*
deb https://akamai.github.io/akr-pkg/debian ./
$ apt-cache madison akr
N: Unable to locate package akr
```

**Comment by nikhilty** [comment]
Hi @lambda-chat, the url has been changed to https://akamai.github.io/akr-pkg/ubuntu. Apologies for the confusion. Please find the updated instructions at https://github.com/akamai/akr-pkg
