### ISSUE TITLE
Ubuntu support

### ISSUE THREAD

**Issue by viggy96** [akamai/akr#23]
I see that Debian/RHEL are supported but not Ubuntu.

**Comment by nikhilty** [comment]
ubuntu is supported too. Follow below steps

```
curl -SsL https://akamai.github.io/akr-pkg/ubuntu/KEY.gpg | sudo apt-key add -
sudo curl -SsL -o /etc/apt/sources.list.d/akr.list https://akamai.github.io/akr-pkg/ubuntu/akr.list
sudo apt update
sudo apt install akr
sudo apt install pinentry-tty

```
 Let me know if you face any issues.

**Comment by laseryuan** [comment]
It seems not working on remote environment like google cloud shell: https://shell.cloud.google.com/?show=terminal

Similar issue as described above.
