### ISSUE TITLE
Multi-device support 

### ISSUE THREAD

**Issue by viggy96** [akamai/akr#24]
Is it possible for the current Android/iOS app to be paired with more than one computer running akr? If not, this should be a feature. 

I used the old kr tool as another way to sync my key between desktops/laptops.

**Comment by skyeatshorizon** [comment]
Would love to see this feature. Otherwise I don't think I can switch to akr

**Comment by nikhilty** [comment]
yes it is possible for the Akamai MFA app to be paired with multiple computers running AKR. Let me know if its not working for you and i can help.
