### ISSUE TITLE
Support for ssh-add with non FIDO2 keys

### ISSUE THREAD

**Issue by qdlmcfresh** [akamai/akr#28]
Would be great to have the option to add a non FIDO2-Key to the agent.
eg. `ssh-add path/to/privkey` should add the key to the agent instead of returning success but not adding it with the message: `add error: not a fido2 ssh keypair` in [ssh_agent.rs](https://github.com/akamai/akr/blob/7d734165d93a489124d0103f41220472b5c3fc1a/crates/kr/src/ssh_agent.rs)

**Comment by parsec** [comment]
i agree, it would be nice to to be able to use this on older (i.e. basically every SSH server still out there, honestly) SSH server versions.

**Comment by nikhilty** [comment]
starting release 1.1.0, ssh-agent will pre-load all RSA, ECDSA and ED25519 keys from ~/.ssh directory on load.
