### ISSUE TITLE
Push notifications on linux and macOS

### ISSUE THREAD

**Issue by agrinman** [akamai/akr#3]
we should still use this on linux, but on macOS should do something like invoke AppleScript or some notification command.

_Originally posted by @agrinman in https://github.com/akamai/akr/pull/1#r659871610_

**Comment by nikhilty** [comment]
Fixed by commenting out 
`let _ = mac_notification_sys::set_application(&"com.akamai.pushzero");`

because of this open [issue](https://github.com/h4llow3En/mac-notification-sys/issues/8) on mac-notification-sys
