### ISSUE TITLE
Cannot setup

### ISSUE THREAD

**Issue by rtfpessoa** [akamai/akr#9]
Hello 👋,

Trying to migrate from kr to akr but getting an error.

Using an M1 mac with an iphone, not sure if this can be the reason to the error.

```
> akr setup
Error: File IO error: 'No such file or directory (os error 2)'
```

~~If I forget about do the setup manually by adding the needed part in `.ssh/config` by hand and start `akr start`,
pair works but if I try to generate a key I get:~~

Today seems like if I start the daemon and generate a key it is working nice, but setup is still broken.

```
> akr start
> akr generate --name ssh
```

**Comment by shanewilson** [comment]
I think I bypassed this by adding the directory `~/Library/LaunchAgents` which didn't exist on my new Monterey install.

Found in the code here:
https://github.com/akamai/akr/blob/master/crates/kr/src/launch.rs#L64-L71

**Comment by kevinchow** [comment]
You have to remove kr installation before installing akr, at this moment most servers don't support sk-ecdsa-sha2-nistp256@openssh.com key (bitbucket, EC2, etc...) so it is almost useless at this point.

**Comment by jzweifel** [comment]
I ran into this same problem. In my case, I was on a brand new install of WSL, and `~/.ssh/config` did not yet exist. When I created the file, `akr setup` completed just fine.

**Comment by nikhilty** [comment]
> I ran into this same problem (`Error: File IO error: 'No such file or directory (os error 2)'`). In my case, I was on a brand new install of WSL, and `~/.ssh/config` did not yet exist. When I created the file, `akr setup` completed just fine.

Glad that worked fine for you.

**Comment by nikhilty** [comment]
> Hello 👋,
> 
> Trying to migrate from kr to akr but getting an error.
> 
> Using an M1 mac with an iphone, not sure if this can be the reason to the error.
> 
> ```
> > akr setup
> Error: File IO error: 'No such file or directory (os error 2)'
> ```
> 
> ~If I forget about do the setup manually by adding the needed part in `.ssh/config` by hand and start `akr start`, pair works but if I try to generate a key I get:~
> 
> Today seems like if I start the daemon and generate a key it is working nice, but setup is still broken.
> 
> ```
> > akr start
> > akr generate --name ssh
> ```

you can use `akr setup --ssh-config-path <ssh_config_file_path>` to configure the ssh config and it will start the daemon as well. Let me know if you face any issues.
